version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Mtt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbitpass

  motorcycle:
    build:
      context: ./MotorcycleService
      dockerfile: Dockerfile
    container_name: motorcycle
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
    ports:
      - "5001:80"

  rental:
    build:
      context: ./RentalMotorcycle
      dockerfile: Dockerfile
    container_name: rental
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
    ports:
      - "5002:80"

  deliveryman:
    build:
      context: ./DeliveryPilots
      dockerfile: Dockerfile
    container_name: deliveryman
    depends_on:
      - postgres
      - mongodb
      - rabbitmq
    ports:
      - "5003:80"

  bff:
    build:
      context: ./BFFService
      dockerfile: Dockerfile
    container_name: bff
    depends_on:
      - motorcycle
      - rental
      - deliveryman
    ports:
      - "5004:80"

  notification:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    container_name: notification
    depends_on:
      - motorcycle
      - rental
      - deliveryman
    ports:
      - "5005:80"

volumes:
  postgres_data:
  mongo_data: